### ISSUE TITLE
Can't install addon after update to 2021.1.3

### ISSUE THREAD

**Issue by cho0p** [einschmidt/hassio-addons#17]
Hi,

I just updated my HA to core-2021.1.3. After the update the Caddy 2 Addon is the only addon which doesn't work anymore.

Tried to re-install the addon but I get the following error:

21-01-16 20:04:25 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install berichta/caddy-2-amd64:0.1.0 -> 404 Client Error for http+docker://localhost/v1.40/images/create?tag=0.1.0&fromImage=berichta%2Fcaddy-2-amd64: Not Found ("manifest for berichta/caddy-2-amd64:0.1.0 not found: manifest unknown: manifest unknown").

Help is very much appreciated :) 

## System Health

version | 2021.1.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-13-amd64
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.9.0
Stage | running
Available Repositories | 773
Installed Repositories | 5

</details>

<details><summary>Hass.io</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | 2021.01.4
docker_version | 19.03.13
disk_total | 105.3 GB
disk_used | 21.9 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Caddy (1.6), MariaDB (2.2.1), Portainer (1.3.0), phpMyAdmin (0.1.4), deCONZ (6.6.0), Check Home Assistant configuration (3.6.0), motionEye (0.10.2), Mosquitto broker (5.1), ESPHome (1.15.3), AppDaemon 4 (0.3.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 9
resources | 2

</details>

**Comment by bouwew** [comment]
Same here.

I think the `repository.json` file needs updating, it still points to the `berichta`-github instead of to the `einschmidt`-github.

**Comment by einschmidt** [comment]
This was in fact a supervisor bug, fixed here: https://github.com/home-assistant/supervisor/pull/2443

The add-ons should be installable again.
