### ISSUE TITLE
Build Caddy with DNS validation

### ISSUE THREAD

**Issue by DavidFW1960** [einschmidt/hassio-addons#3]
Have you considered building Caddy with the legacy DNS addons so we can use the DNS challenge instead of the http one on port 80?

**Comment by einschmidt** [comment]
Hi @DavidFW1960 ,
As mentioned by the creators of the legacy DNS addon, the legacy addon is deprecated and temporary only. As such, I hesitate to build upon the mentioned addon.

Anyway, I think everyone should have the flexibility to build and use whatever suits the own environment. I therefore added the possibility to run custom caddy builds with the add-on. You can create the binary yourself (including whatever addon) and fire it up via the addon. 

All in all, caddy 2 is just out for a short time. I assume there will be new and easier ways to include plugins, configure different challenges etc. soon.

**Comment by DavidFW1960** [comment]
Yeah agreed. I got the impression it’s a stop gap as well. With all the time v2 was in beta I’m surprised the addon is not there yet. 

I’m kind of happy to wait this out for now but I might have to give nginx a try. I detest running stuff that is essentially unsupported and depreciated.
