### ISSUE TITLE
Caddy2 add on custom binary

### ISSUE THREAD

**Issue by dkebler** [einschmidt/hassio-addons#35]
I have a custom binary (has route53dns tls).  

How can I set this up so the addon uses a custom binary?  

I see the yaml has a setting
`  custom_binary_path: str?`

is this a relative relative or absolute path in hassos?

**Comment by einschmidt** [comment]
Hi,

The path should be absolute, here an examples:

```yaml
custom_binary_path: /share/caddy/caddy
```

The above example tries to find a `caddy` binary inside a "caddy" folder, inside the share folder.
Of course, any other accessible folder should work as well.

By the way, accessible are any folders below:
- share
- config
- ssl

Hope that helps, otherwise let me know.

**Comment by einschmidt** [comment]
Further explanations can also be found in the documentation.

https://github.com/einschmidt/hassio-addons/blob/main/caddy-2/DOCS.md#updatesplugins

**Comment by dkebler** [comment]
THANKS! I have that working perfectly using a Caddyfile  

I did determine that addon only uses the Caddyfile adapter if using the filename Caddyfile.  If I want someting else then I guess I need to specifically set the commandline adapter switch (how to add commandline switches? via environment?)

SO Now I'm wondering about the 

`  caddy_upgrade: bool?`

is that setting supposed to update a binary with particular plugin from here?
e.g.
https://caddyserver.com/download?package=github.com%2Fcaddy-dns%2Froute53

if so what setting holds the the url?  If not then this should be a new feature as caddy2 now makes it easy (again) to build/download a custom binary :).

**Comment by einschmidt** [comment]
> If I want someting else then I guess I need to specifically set the commandline adapter switch (how to add commandline switches? via environment?)

Check the args option:
https://github.com/einschmidt/hassio-addons/blob/main/caddy-2/DOCS.md#option-args

> caddy_upgrade: bool?
is that setting supposed to update a binary with particular plugin from here?

See here: https://github.com/einschmidt/hassio-addons/blob/main/caddy-2/DOCS.md#option-caddy_upgrade

A proper `caddy_upgrade` setting looks like the following:
```yaml
caddy_upgrade: true
```

When set to `true`, the addon will update any binary upon launch, automatically, including any plugins.

**Comment by DavidFW1960** [comment]
> When set to `true`, the addon will update any binary upon launch, automatically, if necessary, including any plugins.

it also does this everytime the addon is started even if the installed Caddy is the correct current version.
