### ISSUE TITLE
Repository can no longer be added to the addon store

### ISSUE THREAD

**Issue by Paul-Vdp** [einschmidt/hassio-addons#37]
When trying to add the repository, it was refused with 'Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/einschmidt/addon-caddy-2/tree/main/caddy-2 /data/addons/git/409fd3ef stderr: 'Cloning into '/data/addons/git/409fd3ef'... fatal: repository 'https://github.com/einschmidt/addon-caddy-2/tree/main/caddy-2/' not found '

**Comment by einschmidt** [comment]
Hi @Paul-Vdp,

Please can you check the URL that you have used?

It should be the following:

```
https://github.com/einschmidt/hassio-addons
```

**Comment by Paul-Vdp** [comment]
Hi @einschmidt . Thx for coming back on it. I'm afraid I can confirm I used the correct path (used copy/paste to fill it in, so should be correct).
Funny thing is that in another location/installation where I have been using your addon for years already, the addon is still present and working, but the repository itself is nowhere to be found anymore - it just disappeared from the list. And also in this installation it is impossible to add it again, with the same error ...
The error seems to point to some fault in the github path of the caddy addon, no ?

**Comment by einschmidt** [comment]
Thanks for checking @Paul-Vdp !

I looked into the HA Forum and found following entry with the same failure:

https://community.home-assistant.io/t/supervisor-error-can-t-retrieve-data-from-repository-link-can-t-clone-repository-link-cmd-git-failed-due-to-exit-code-128/436546/13

Please can you check your DNS settings inside HA?

Also, would be interesting to know whether you can add other repositories. Could you try some?

**Comment by Paul-Vdp** [comment]
@einschmidt I'm using DHCP, and consequently DNS settings have not changed for ages.
Besides, your repo is the only one that 'disappeared' from the one installation, none of the others did this ?
And I tried to add another repo as you asked, and this got easily added without any fuss ...

**Comment by Paul-Vdp** [comment]
After a lot of restarts AND disabling Adguard I finally succeeded in adding your repo and installing the addon.
Do not know what exactly did the trick, but thanks anyway for your support !

**Comment by einschmidt** [comment]
Thanks for the update, I am glad to hear it works now. 👍

**Comment by Stooovie** [comment]
I have added a lot of different repositories but this one can not be added at all. DNS is my ISP's

Edit: worked after an 8th try
