### ISSUE TITLE
Freshrss - addon vs standalone?

### ISSUE THREAD

**Issue by quartzbear** [einschmidt/hassio-addons#39]
Hi,

Thanks for the add-ons. are there any drawbacks using the Freshrss add-on vs a standalone (docker etc) version?

**Comment by einschmidt** [comment]
Hi @quartzbear 

In terms of core functionality, not much difference, if at all.

The only difference i could think of are custom plugins and themes, which you may want to add. It is easier with the original docker, as i have not integrated any config possibility yet. Having that said, there was also no request or requirement yet, as i am using freshrss for the provided API.

**Comment by quartzbear** [comment]
I don't currently use any plugins with my current Freshrss, so i'd say this would work for me.
Thanks
