### ISSUE TITLE
Version 2.0.0.0 of Caddy 2 breaks things

### ISSUE THREAD

**Issue by McTristan** [einschmidt/hassio-addons#44]
I'm afraid the latest version of caddy 2 breaks things. 

It no longer finds the Caddyfile.

The documentation states I should put the Caddyfile now under 

addons_config/c80c7555_caddy-2

which I did. Even though my server name is 2e2eff1f_caddy-2.

I did also try to put in the the root (i.e. /config) path but whenever I start the add on it always says: 

INFO: Prepare Caddyfile...
INFO: No Caddyfile found
INFO: Use non_caddyfile_config
INFO: Run Caddy...

Of course I restarted the add on multiple times.

**Comment by einschmidt** [comment]
Hi @McTristan,
Thanks for reaching out.

The folder name (and especially the repository reference) should be based on the URL. Thus, I assumed it would be c80c7555 for everyone. Thanks for mentioning your folder name.
The folder should be auto-generated.

Please ensure that your Caddyfile is named `Caddyfile` with capital C.

Next to the name, there is nothing else to consider.

Let me know if naming the file solves the issue.

**Comment by McTristan** [comment]
Of course I have it named correctly, the file is called Caddyfile without extension - in fact I had one before and just copied it over. 

I re-installed the addon to check if it creates any folder but it seems it doesn't and even when I create the directory it does not find the file.

**Comment by einschmidt** [comment]
Just a few checks, to be sure:

The full folder path would be `/addon_configs/<ref>_caddy-2`.

The above folder, and especially the addon_configs folder, lies in root.

`/config` is not the root folder, and holds the HA config.

**Comment by McTristan** [comment]
ok the <ref>-part seems to be important, for me it is 2e2eff1f. 

I realized I had no other subdirectories unter /addon_configs so I checked the permission and it seemed I had them wrong.
After setting the correct permission and reinstalling the addon I realized there was indeed a new sub-folder. 
Put my Caddyfile there, restarted the addon - et voila.
